# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/149MCyQZRrXVyJp63fuEPPBmAD7g9uvCA
"""

pip install geopy

import pandas as pd
from geopy.geocoders import Nominatim
from geopy.exc import GeocoderTimedOut
from geopy.extra.rate_limiter import RateLimiter

df = pd.read_csv('project-1.csv')

df.head()

df2 = df.dropna(axis=1) # through axis = 1 we specifically target the columns not the rows.

df2.head()

df2['fullname'] = df2['First'] + ' ' + df2['Last']

df2.head()

df2.tail()

df2['Time'] = pd.to_timedelta(df2['Time'])

df2['Total_Minutes'] = df2['Time'].dt.total_seconds()/60

df2['Total_Minutes'] = df2['Total_Minutes'].round().astype(int)

df2.head()

df2.rename(columns={ 'Division': 'Gender' }, inplace=True)

df2.head()

def get_lat_long(city, state):
  address = f"{city}, {state}"
  try:
    geolocator = Nominatim(user_agent="running", timeout=10)
    location = geolocator.geocode(address)
    if location:
      return location.latitude, location.longitude
    else:
      return None, None
  except GeocoderTimedOut:
    return None, None

df2['latitude'], df2['longitude'] = zip(*df2.apply(lambda x: get_lat_long(x['City'], x['State']), axis=1))

df2.head()

df2['latlong'] = df2['latitude'].astype(str) + ', ' + df2['longitude'].astype(str)

df2.head()

df2.to_csv('project1_output.csv', index=False)

